### ISSUE TITLE
Reboot loop after install

### ISSUE THREAD

**Issue by chrisfraser** [Jacotheron/D5S-Repetier-Firmware#1]
Hi Jaco

I have installed the latest firmware and get a continuous boot loop after install. Below is a sample of the console output. Is there something I am doing wrong?

```
start
Free RAM:2892
start
start
Free RAM:2892
SelectExtruder:0
FlowMultiply:100
wait
start
Free RAM:2892
start
Free RAM:2892
start
Free RAM:2892
Sstart
Free RAM:2892
Sstart
Free RAM:2892
start
Free RAM:2892
Sstart
Free RAM:2892
start
Free RAM:2892
start
Free RAM:2892
Sstart
```

**Comment by Jacotheron** [comment]
Which version of Arduino did you use to flash the firmware? I tested it with 1.6.12.

I have also seen this boot loop issue myself, no idea what causes it (mine went away after a few flashing and using older versions of the IDE). If have trouble, try an older version of Arduino IDE.

**Comment by chrisfraser** [comment]
Ok cool. I will roll back to 1.6.0 and give it a try.

**Comment by chrisfraser** [comment]
I have tried many versions of Arduino (1.5.x, 1.6.0, 1.6.5, 1.6.12) and all the released Repetier versions in your repo. Still get the same flashing LCD with version and logo, then reboot. Any other suggestions? My board looks exactly like this one: http://wanhaousa.com/collections/electronics-d5/products/micro-controller

**Comment by Jacotheron** [comment]
That mainboard is a new type, but it is compatible (I have installed it personally on one of them).

Having just done a little bit of research, it is called a bootloop, and can possible happen when the Watchdog is triggered (possibly by flashing the firmware). To solve this, the watchdog need to completely power down, before getting restarted.

So completely disconnect the power and USB from the printer for a short while, plug it back in and see if you can get past the boot screen.

**Comment by chrisfraser** [comment]
No luck. Even tried setting `FEATURE_WATCHDOG 0`. I will try debug it over the weekend. Do you think programming via ICSP would help? There are also two MCUs on the board. There is a 16U dealing with USB comms.

**Comment by Jacotheron** [comment]
ISCP programming might work, the big MCU on the right (of the Wanhao USA link you provided) is the AtMega2560 chip (the one that should handle the firmware).

I will also try to find other possible causes.

**Comment by Jacotheron** [comment]
I have been unable to find more information which might help you. Are you able to revert to other firmware?

**Comment by Jacotheron** [comment]
It seems that this issue can be caused by having more than one language enabled, so best is to just have one language enabled (change was made in the firmware).
